services:
  db:
    image: 'postgres:latest'
    ports:
      - 15432:5432
    volumes:
      - dbstore:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: oresai
      POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: /var/lib/postgresql/data/some_name/

volumes:
  dbstore:
